### ISSUE TITLE
用不了，sad。

### ISSUE THREAD

**Issue by dyguests** [mybichu/PyGetterAndSetter#1]
点击后无反应。。。

**Comment by neoyu123** [comment]
> 点击后无反应。。。

看一下你的版本是不是最新的，老版本的我没有验证。
博客地址：https://www.cnblogs.com/yuxiuyan/p/15359781.html

**Comment by neoyu123** [comment]
<img width="549" alt="use_plugin" src="https://user-images.githubusercontent.com/20676047/198793476-bbf5920d-9dbd-4d29-aa69-056a06967cdf.png">

我在Mac OS 12.5  Pycharm 2022.2试了一下是可以的。你要看一下是否把属性行的内容全部选中了。
