### ISSUE TITLE
pycharm 2022.1没用 难受香菇 

### ISSUE THREAD

**Issue by CheerMan1** [mybichu/PyGetterAndSetter#2]

**Comment by neoyu123** [comment]
我在Mac OS 12.5   Pycharm 2022.2  版本上可以用的，你看看是否是没有把定义属性的行的内容全部选中导致的呢。

**Comment by neoyu123** [comment]
<img width="549" alt="use_plugin" src="https://user-images.githubusercontent.com/20676047/198793245-9ed700d6-2c20-4d0e-b823-ba69e1028616.png">
